# -*- coding: utf-8 -*-
"""text_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gofA1pDOboE1fjdxzXOaEiJUzEnAv9KT
"""

pip install easyocr

pip install pymupdf

import fitz
import easyocr

# Initialize OCR
reader = easyocr.Reader(['en'])

# Open PDF
pdf = fitz.open("scanned.pdf")

all_text = ""

for page_num in range(len(pdf)):
    page = pdf.load_page(page_num)

    # Convert page to image
    pix = page.get_pixmap(dpi=300)

    image_path = f"page_{page_num}.png"
    pix.save(image_path)

    # OCR
    result = reader.readtext(image_path, detail=0)

    page_text = "\n".join(result)

    all_text += f"\n\n===== Page {page_num + 1} =====\n"
    all_text += page_text

# Save to text file
with open("extracted_text.txt", "w", encoding="utf-8") as file:
    file.write(all_text)

print("OCR text saved successfully to extracted_text.txt")

!ls /content

from google.colab import drive
drive.mount('/content/drive')

with open("/content/drive/MyDrive/extracted_text.txt", "w", encoding="utf-8") as file:
    file.write(all_text)