"""
Unit tests for Landmark Case Agent (src/landmark_case_agent.py).

Mocks retrieve_case_law and call_llm_structured to verify:
  (1) A normal case returns cases with source URLs copied exactly from the
      mocked metadata (not from the mocked LLM text or hallucinations).
  (2) No retrieved cases returns status 'no_relevant_cases' with an empty list.
  (3) Malformed LLM response for one case's explanation doesn't crash the whole
      function - other cases still return normally with their explanations.

Run:
  python tests/test_landmark_case_agent.py
  or: pytest tests/test_landmark_case_agent.py
"""

import json
import sys
from pathlib import Path
from unittest.mock import patch

# Ensure src is in sys.path
src_dir = Path(__file__).resolve().parent.parent / "src"
if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

from landmark_case_agent import find_landmark_cases


def test_normal_case_copies_source_url_from_metadata():
    """
    Verify that source_url is strictly copied programmatically from chunk metadata,
    ignoring any hallucinated URLs or text generated by the LLM.
    """
    case_brief = {
        "domain": "Consumer Protection",
        "facts": {
            "what_was_bought_or_hired": "Luxury Car",
            "what_went_wrong": "Sunroof leaks repeatedly damaging electronics; dealer and manufacturer refuse to take responsibility",
            "amount_paid": "4500000 INR",
            "seller_or_provider": "Volkswagen Dealer",
        },
        "ready": True,
    }

    mock_retrieved_cases = [
        {
            "id": "case_134120181",
            "text": "The Commission clarified the scope of liability in a Principal to Principal relationship...",
            "metadata": {
                "case_title": "H.G. Jain vs Volkswagen India Pvt. Ltd. & 2 Ors. on 14 July, 2025",
                "court": "National Consumer Disputes Redressal",
                "date": "2025-07-14",
                "source_url": "https://indiankanoon.org/doc/134120181/",
                "attribution": "Powered by Indian Kanoon (https://indiankanoon.org)",
            },
            "distance": -25.5,
        },
        {
            "id": "case_193735273",
            "text": "The State Commission held that both dealer and manufacturer are jointly liable...",
            "metadata": {
                "case_title": "Wsl Automobiles vs Fca India Automobiles Pvt. Ltd. And ... on 7 January, 2026",
                "court": "State Consumer Disputes Redressal Commission",
                "date": "2026-01-07",
                "source_url": "https://indiankanoon.org/doc/193735273/",
                "attribution": "Powered by Indian Kanoon (https://indiankanoon.org)",
            },
            "distance": -24.1,
        },
    ]

    # LLM payload contains hallucinated URL inside explanation text or separate field
    llm_payload_1 = {
        "relevance_explanation": (
            "In this precedent, the Commission held that manufacturers cannot escape liability for manufacturing "
            "defects despite having independent dealer agreements. This directly applies to your leaking sunroof dispute."
        ),
        "hallucinated_url": "https://hallucinated-legal-source.com/fake/99999",
    }
    llm_payload_2 = {
        "relevance_explanation": (
            "This decision holds both dealer and manufacturer jointly liable for unresolved vehicle defects. "
            "It supports holding both parties accountable in your case."
        )
    }

    mock_llm_responses = [json.dumps(llm_payload_1), json.dumps(llm_payload_2)]

    with patch("landmark_case_agent.retrieve_case_law", return_value=mock_retrieved_cases) as mock_retrieve, \
         patch("landmark_case_agent.call_llm_structured", side_effect=mock_llm_responses) as mock_llm:
        result = find_landmark_cases(case_brief)

    assert result["status"] == "found", f"Expected status 'found', got {result['status']}"
    assert len(result["cases"]) == 2, f"Expected 2 cases, got {len(result['cases'])}"

    # CRITICAL CHECK: Ensure source_url is exactly from metadata
    assert result["cases"][0]["source_url"] == "https://indiankanoon.org/doc/134120181/"
    assert result["cases"][0]["case_title"] == "H.G. Jain vs Volkswagen India Pvt. Ltd. & 2 Ors. on 14 July, 2025"
    assert result["cases"][0]["court"] == "National Consumer Disputes Redressal"
    assert result["cases"][0]["date"] == "2025-07-14"
    assert result["cases"][0]["attribution"] == "Powered by Indian Kanoon (https://indiankanoon.org)"
    assert "cannot escape liability" in result["cases"][0]["relevance_explanation"]

    assert result["cases"][1]["source_url"] == "https://indiankanoon.org/doc/193735273/"
    assert result["cases"][1]["case_title"] == "Wsl Automobiles vs Fca India Automobiles Pvt. Ltd. And ... on 7 January, 2026"
    assert "jointly liable" in result["cases"][1]["relevance_explanation"]

    assert mock_retrieve.called
    assert mock_retrieve.call_args[1]["top_k"] == 3
    assert mock_llm.call_count == 2
    print("  Normal case test passed: Source URLs correctly copied from metadata, LLM explanations grounded.")


def test_no_retrieved_cases_returns_no_relevant_cases():
    """
    Verify that when retrieval returns no candidates or when facts are empty,
    the agent returns status 'no_relevant_cases' with an empty list.
    """
    case_brief = {
        "domain": "Consumer Protection",
        "facts": {
            "what_was_bought_or_hired": "Unrelated product",
            "what_went_wrong": "Unrelated issue",
        },
        "ready": True,
    }

    # Case A: Vector store returns empty list
    with patch("landmark_case_agent.retrieve_case_law", return_value=[]) as mock_retrieve, \
         patch("landmark_case_agent.call_llm_structured") as mock_llm:
        result = find_landmark_cases(case_brief)

    assert result["status"] == "no_relevant_cases"
    assert result["cases"] == []
    assert mock_retrieve.called
    assert not mock_llm.called  # LLM should never be called if no candidates retrieved

    # Case B: Empty or missing facts
    empty_brief = {"domain": "Consumer Protection", "facts": {}}
    res_empty = find_landmark_cases(empty_brief)
    assert res_empty["status"] == "no_relevant_cases"
    assert res_empty["cases"] == []

    # Case C: Invalid input
    res_invalid = find_landmark_cases(None)
    assert res_invalid["status"] == "no_relevant_cases"
    assert res_invalid["cases"] == []

    print("  No retrieved cases test passed: Correctly returned 'no_relevant_cases'.")


def test_malformed_llm_response_handled_gracefully():
    """
    Verify that if the LLM output for one case is corrupt or fails to parse,
    that case falls back gracefully to a generic sentence and other cases still
    return normally without crashing the whole function.
    """
    case_brief = {
        "domain": "Consumer Protection",
        "facts": {
            "what_was_bought_or_hired": "Air Conditioner",
            "what_went_wrong": "Defective compressor on arrival",
        },
        "ready": True,
    }

    mock_retrieved_cases = [
        {
            "id": "case_1",
            "text": "Reasoning text for Case 1...",
            "metadata": {
                "case_title": "Case 1 Title",
                "court": "State Consumer Commission",
                "date": "2024-01-01",
                "source_url": "https://indiankanoon.org/doc/11111/",
                "attribution": "Powered by Indian Kanoon",
            },
            "distance": -20.0,
        },
        {
            "id": "case_2",
            "text": "Reasoning text for Case 2...",
            "metadata": {
                "case_title": "Case 2 Title",
                "court": "National Consumer Commission",
                "date": "2024-02-02",
                "source_url": "https://indiankanoon.org/doc/22222/",
                "attribution": "Powered by Indian Kanoon",
            },
            "distance": -19.0,
        },
    ]

    # First call returns corrupt non-JSON, second call returns valid JSON
    mock_llm_side_effects = [
        "This is not JSON at all: {broken",
        json.dumps({"relevance_explanation": "Valid 2-3 sentence legal explanation for Case 2."}),
    ]

    with patch("landmark_case_agent.retrieve_case_law", return_value=mock_retrieved_cases), \
         patch("landmark_case_agent.call_llm_structured", side_effect=mock_llm_side_effects):
        result = find_landmark_cases(case_brief)

    assert result["status"] == "found"
    assert len(result["cases"]) == 2

    # Case 1 should not crash, but have a fallback explanation and correct metadata
    assert result["cases"][0]["case_title"] == "Case 1 Title"
    assert result["cases"][0]["source_url"] == "https://indiankanoon.org/doc/11111/"
    assert len(result["cases"][0]["relevance_explanation"]) > 0
    assert "establishes legal principles" in result["cases"][0]["relevance_explanation"]

    # Case 2 should have the valid explanation parsed from the LLM
    assert result["cases"][1]["case_title"] == "Case 2 Title"
    assert result["cases"][1]["source_url"] == "https://indiankanoon.org/doc/22222/"
    assert result["cases"][1]["relevance_explanation"] == "Valid 2-3 sentence legal explanation for Case 2."

    print("  Malformed LLM test passed: Fail-safe fallback succeeded without crashing the batch.")


if __name__ == "__main__":
    tests = [
        test_normal_case_copies_source_url_from_metadata,
        test_no_retrieved_cases_returns_no_relevant_cases,
        test_malformed_llm_response_handled_gracefully,
    ]
    print("\nRunning Landmark Case Agent Unit Tests:")
    for t in tests:
        print(f"\n{t.__name__}:")
        t()
    print("\nAll Landmark Case Agent tests passed successfully!")
